aws_region                 = "us-west-2"
env                        = "prod-hub"
vpc_cidr                   = "10.0.0.0/16"
availability_zones         = ["us-west-2a", "us-west-2b"]
public_subnets             = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets            = "10.0.10.0/24"
admin_cidr                 = "0.0.0.0/0"
public_key_path            = "../../ssh-keys/aws-key.pub"
enable_deletion_protection = false
